import SwiftUI

// Generated by Supernova - do not modify manually
public extension View {

    func borderBorderSmall() -> some View {
        return self.border(Color(.sRGB, red: 229/255, green: 229/255, blue: 234/255, opacity: 1), width: 1) 
    }

    func borderBorderDefault() -> some View {
        return self.border(Color(.sRGB, red: 229/255, green: 229/255, blue: 234/255, opacity: 1), width: 2) 
    }

    func borderBorderFocussed() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), width: 2) 
    }
}