import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleLargeTitle() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 34))
    }

    func textStyleTitle() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 28))
    }

    func textStyleTitle2() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 22))
    }

    func textStyleTitle3() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 20))
    }

    func textStyleHeadline() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 17))
    }

    func textStyleSubHeadline() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 15))
    }

    func textStyleBody() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 17))
    }

    func textStyleCallout() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 16))
    }

    func textStyleCallout2() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 16))
    }

    func textStyleFootnote() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 13))
    }

    func textStyleCaption() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 12))
    }

    func textStyleCaption2() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 11))
    }
}
