import SwiftUI

// Generated by Supernova - do not modify manually
import SwiftUI

// Generated by Supernova - do not modify manually
public extension Text {

    func textStyleLargeTitle() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 34))
    }

    func textStyleTitle() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 28))
    }

    func textStyleTitle2() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 22))
    }

    func textStyleTitle3() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 20))
    }

    func textStyleHeadline() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 17))
    }

    func textStyleSubHeadline() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 15))
    }

    func textStyleBody() -> some View {
        return self
            .font(Font.custom("Inter-Bold", size: 17))
    }

    func textStyleCallout() -> some View {
        return self
            .font(Font.custom("Inter-Regular", size: 16))
    }

    func textStyleCallout2() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 16))
    }

    func textStyleFootnote() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 13))
    }

    func textStyleCaption() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 12))
    }

    func textStyleCaption2() -> some View {
        return self
            .font(Font.custom("Inter-Medium", size: 11))
    }
}

//Jay
public extension Font {

    static func textStyleLargeTitle() -> Font {
        .custom("Inter-Bold", size: 34)
    }

    static func textStyleTitle() -> Font {
        .custom("Inter-Bold", size: 28)
    }

    static func textStyleTitle2() -> Font {
        .custom("Inter-Bold", size: 22)
    }

    static func textStyleTitle3() -> Font {
        .custom("Inter-Bold", size: 20)
    }

    static func textStyleHeadline() -> Font {
        .custom("Inter-Bold", size: 17)
    }

    static func textStyleSubHeadline() -> Font {
        .custom("Inter-Medium", size: 15)
    }

    static func textStyleBody() -> Font {
        .custom("Inter-Bold", size: 17)
    }

    static func textStyleCallout() -> Font {
        .custom("Inter-Regular", size: 16)
    }

    static func textStyleCallout2() -> Font {
        .custom("Inter-Medium", size: 16)
    }

    static func textStyleFootnote() -> Font {
        .custom("Inter-Medium", size: 13)
    }

    static func textStyleCaption() -> Font {
        .custom("Inter-Medium", size: 12)
    }

    static func textStyleCaption2() -> Font {
        .custom("Inter-Medium", size: 11)
    }
}
