import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {
        public let kfhBrand = Color(.sRGB, red: 154/255, green: 205/255, blue: 50/255, opacity: 1) 
        public let black = Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1) 
        public let white = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let systemGray = Color(.sRGB, red: 142/255, green: 142/255, blue: 147/255, opacity: 1) 
        public let systemGray2 = Color(.sRGB, red: 99/255, green: 99/255, blue: 102/255, opacity: 1) 
        public let systemGray3 = Color(.sRGB, red: 199/255, green: 199/255, blue: 204/255, opacity: 1) 
        public let systemGray4 = Color(.sRGB, red: 209/255, green: 209/255, blue: 214/255, opacity: 1) 
        public let systemGray5 = Color(.sRGB, red: 229/255, green: 229/255, blue: 234/255, opacity: 1) 
        public let systemGray6 = Color(.sRGB, red: 242/255, green: 242/255, blue: 247/255, opacity: 1) 
        public let disabled = Color(.sRGB, red: 153/255, green: 153/255, blue: 153/255, opacity: 1) 
        public let systemBlue = Color(.sRGB, red: 0/255, green: 122/255, blue: 255/255, opacity: 1) 
        public let systemRed = Color(.sRGB, red: 255/255, green: 59/255, blue: 48/255, opacity: 1) 
    }
}